server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mayproject?serverTimezone=UTC&character=utf-8
    username: root
    password: root
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      example:
        demo:
          mapper: debug

